### ISSUE TITLE
Build fails (BasicAuth undefined)

### ISSUE THREAD

**Issue by photm5** [openlab-aux/lsmsd#1]
When I try to build with `go get github.com/openlab-aux/lsmsd`, it errors with

```
$GOPATH/src/github.com/openlab-aux/lsmsd/backend/auth.go:31: request.Request.BasicAuth undefined (type *http.Request has no field or method BasicAuth)
```

**Comment by glaxx** [comment]
Which version of Go do you have installed?

From my point of view you're trying to compile this code with an outdated version (<1.4) of the Go environment.

**Comment by muesli** [comment]
BasicAuth is indeed only available with Go >=1.4. I took the liberty to add this project to travis so we can track our Go dependencies.

**Comment by glaxx** [comment]
@muesli Thank you!

**Comment by muesli** [comment]
Also updated the README to mention the 1.4 dep. Closing this issue as I don't think it's reasonable to work around for older Go versions.
