### ISSUE TITLE
Tree structure with parent references

### ISSUE THREAD

**Issue by salomonderossi** [openlab-aux/lsmsd#3]
In my opinion it makes more sense to model a tree structure with parent references. it is much easier to change the parent field (one value) rather than a list of children.

See: http://docs.mongodb.org/manual/tutorial/model-tree-structures-with-parent-references/

**Comment by waaaaargh** [comment]
As discussed with @glaxx IRL, having both a list of children and a parent backref (and exposing them to the API) might be beneficial IMHO.

**Comment by salomonderossi** [comment]
Why both? I think we should define what our requirement are and then decide for a model that fits. To use both models makes it needlessly complicated.

IMHO it boils down to the question:

**Do we need multiple parents?**
- yes: Use a list of children
- no: Use parent backref

At the moment I do not see the need for multiple parents... So my vote goes to parent backref ;-)

**Comment by glaxx** [comment]
At the moment I tend towards parent references. 

@waaaaargh would you be so kind to explain why implementing both might be beneficial?

**Comment by salomonderossi** [comment]
I would also be eagerly interested in @muesli 's opinion

**Comment by muesli** [comment]
"It depends..."

Parent refs:
Pro: Consistent, automatically updated when children get deleted. Hard to cock it up.
Con: No ordering of children, querying all children of a parent can be expensive.

Child refs:
Pro: Ordering of children possible. Quick to get a list of an item's children.
Con: Less implied consistency, easy to forget to remove a child when deleting it.

Bidirectional refs:
Pro: Fast to retrieve data, no matter your approach: parent(s) for children, children for parent(s)
Con: Less implied consistency, easy to forget to remove items when deleting/moving them.

Branches and leaves:
Pro: Incredibly flexible, can point to (sub-)tree items.
Con: Easy to fuck it up, self-referencing awareness / looping logic required

Neste... oh fuck my life.
